import type { ContentItem } from "@/types/content";

// Mock data for content items
export const mockContentItems: ContentItem[] = [
  {
    id: "content-1",
    content: "This platform is terrible and everyone who uses it is stupid.",
    contentType: "post",
    mediaType: "text",
    status: "reported",
    postedAt: "2023-05-15T10:30:00Z",
    reports: 12,
    flaggedReason: "Hate speech",
    aiScore: 87,
    user: {
      id: "user-1",
      name: "John Smith",
      avatar: "/placeholder.svg?height=40&width=40",
    },
  },
  {
    id: "content-2",
    content:
      "Check out my new NFT collection! It's going to be worth millions soon.",
    contentType: "post",
    mediaType: "image",
    mediaUrl: "/placeholder.svg?height=400&width=600",
    status: "pending",
    postedAt: "2023-05-14T15:45:00Z",
    reports: 5,
    flaggedReason: "Spam/Scam",
    aiScore: 62,
    user: {
      id: "user-2",
      name: "Emma Johnson",
      avatar: "/placeholder.svg?height=40&width=40",
    },
  },
  {
    id: "content-3",
    content:
      "I disagree with the new policy changes. They seem to favor certain groups.",
    contentType: "comment",
    mediaType: "text",
    status: "approved",
    postedAt: "2023-05-13T09:15:00Z",
    reports: 2,
    flaggedReason: "Misinformation",
    aiScore: 35,
    user: {
      id: "user-3",
      name: "Michael Brown",
      avatar: "/placeholder.svg?height=40&width=40",
    },
  },
  {
    id: "content-4",
    content: "Here's my tutorial on how to use the new features.",
    contentType: "post",
    mediaType: "video",
    mediaUrl:
      "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    status: "approved",
    postedAt: "2023-05-12T14:20:00Z",
    reports: 0,
    flaggedReason: "",
    aiScore: 12,
    user: {
      id: "user-4",
      name: "Sarah Wilson",
      avatar: "/placeholder.svg?height=40&width=40",
    },
  },
  {
    id: "content-5",
    content:
      "This is completely false information. The government is lying to us about everything.",
    contentType: "comment",
    mediaType: "text",
    status: "reported",
    postedAt: "2023-05-11T11:30:00Z",
    reports: 8,
    flaggedReason: "Misinformation",
    aiScore: 78,
    user: {
      id: "user-5",
      name: "David Lee",
      avatar: "/placeholder.svg?height=40&width=40",
    },
  },
  {
    id: "content-6",
    content: "This platform is terrible and everyone who uses it is stupid.",
    contentType: "post",
    mediaType: "text",
    status: "reported",
    postedAt: "2023-05-15T10:30:00Z",
    reports: 12,
    flaggedReason: "Hate speech",
    aiScore: 87,
    user: {
      id: "user-1",
      name: "John Smith",
      avatar: "/placeholder.svg?height=40&width=40",
    },
  },
  {
    id: "content-7",
    content:
      "Check out my new NFT collection! It's going to be worth millions soon.",
    contentType: "post",
    mediaType: "image",
    mediaUrl: "/placeholder.svg?height=400&width=600",
    status: "pending",
    postedAt: "2023-05-14T15:45:00Z",
    reports: 5,
    flaggedReason: "Spam/Scam",
    aiScore: 62,
    user: {
      id: "user-2",
      name: "Emma Johnson",
      avatar: "/placeholder.svg?height=40&width=40",
    },
  },
  {
    id: "content-8",
    content:
      "I disagree with the new policy changes. They seem to favor certain groups.",
    contentType: "comment",
    mediaType: "text",
    status: "approved",
    postedAt: "2023-05-13T09:15:00Z",
    reports: 2,
    flaggedReason: "Misinformation",
    aiScore: 35,
    user: {
      id: "user-3",
      name: "Michael Brown",
      avatar: "/placeholder.svg?height=40&width=40",
    },
  },
  {
    id: "content-9",
    content: "Here's my tutorial on how to use the new features.",
    contentType: "post",
    mediaType: "video",
    mediaUrl:
      "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    status: "approved",
    postedAt: "2023-05-12T14:20:00Z",
    reports: 0,
    flaggedReason: "",
    aiScore: 12,
    user: {
      id: "user-4",
      name: "Sarah Wilson",
      avatar: "/placeholder.svg?height=40&width=40",
    },
  },
  {
    id: "content-10",
    content:
      "This is completely false information. The government is lying to us about everything.",
    contentType: "comment",
    mediaType: "text",
    status: "reported",
    postedAt: "2023-05-11T11:30:00Z",
    reports: 8,
    flaggedReason: "Misinformation",
    aiScore: 78,
    user: {
      id: "user-5",
      name: "David Lee",
      avatar: "/placeholder.svg?height=40&width=40",
    },
  },
  {
    id: "content-11",
    content: "This platform is terrible and everyone who uses it is stupid.",
    contentType: "post",
    mediaType: "text",
    status: "reported",
    postedAt: "2023-05-15T10:30:00Z",
    reports: 12,
    flaggedReason: "Hate speech",
    aiScore: 87,
    user: {
      id: "user-1",
      name: "John Smith",
      avatar: "/placeholder.svg?height=40&width=40",
    },
  },
  {
    id: "content-12",
    content:
      "Check out my new NFT collection! It's going to be worth millions soon.",
    contentType: "post",
    mediaType: "image",
    mediaUrl: "/placeholder.svg?height=400&width=600",
    status: "pending",
    postedAt: "2023-05-14T15:45:00Z",
    reports: 5,
    flaggedReason: "Spam/Scam",
    aiScore: 62,
    user: {
      id: "user-2",
      name: "Emma Johnson",
      avatar: "/placeholder.svg?height=40&width=40",
    },
  },
  {
    id: "content-13",
    content:
      "I disagree with the new policy changes. They seem to favor certain groups.",
    contentType: "comment",
    mediaType: "text",
    status: "approved",
    postedAt: "2023-05-13T09:15:00Z",
    reports: 2,
    flaggedReason: "Misinformation",
    aiScore: 35,
    user: {
      id: "user-3",
      name: "Michael Brown",
      avatar: "/placeholder.svg?height=40&width=40",
    },
  },
  {
    id: "content-14",
    content: "Here's my tutorial on how to use the new features.",
    contentType: "post",
    mediaType: "video",
    mediaUrl:
      "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    status: "approved",
    postedAt: "2023-05-12T14:20:00Z",
    reports: 0,
    flaggedReason: "",
    aiScore: 12,
    user: {
      id: "user-4",
      name: "Sarah Wilson",
      avatar: "/placeholder.svg?height=40&width=40",
    },
  },
  {
    id: "content-15",
    content:
      "This is completely false information. The government is lying to us about everything.",
    contentType: "comment",
    mediaType: "text",
    status: "reported",
    postedAt: "2023-05-11T11:30:00Z",
    reports: 8,
    flaggedReason: "Misinformation",
    aiScore: 78,
    user: {
      id: "user-5",
      name: "David Lee",
      avatar: "/placeholder.svg?height=40&width=40",
    },
  },
];
